### ISSUE TITLE
Reverse HTTP support

### ISSUE THREAD

**Issue by thejhh** [norjs/portal-service#12]
Support to connect a route behind a NAT to the portal through [Reverse HTTP](https://tools.ietf.org/html/draft-lentczner-rhttp-00) connection.

This also makes it possible to not need to store SSL certificate key on the application "server" side, eg. only store it on a simpler and secured proxy side, as well as no need to open the micro service to the world directly.

The server side (which will turn in to client and route requests to /db to the remote service) would have a configuration like: 

```json
{
  "routes": {
    "/db": {
      "type": "ptth",
      "development": true,
      "production": true
    }
  }
}
```

***Note!*** This will be publicly open, with no authentication. The authentication part can be configured normally and is not part of this feature.

The client (which will get requests after a successful connection) would have a configuration like: 

```json
  "routes": {
    "/db": {
      "ptth": "http://localhost:3000/db",
      "socket": "./database-service.socket",
      "development": true,
      "production": true
    }
  }
```

### TODO

 * [x]  Proof of Concept implementation
 * [x]  `ptth` listening & routing support
 * [x]  `ptth` connection support
 * [x]   Support to configure multiple connection targets using an array instead of a string

**Comment by thejhh** [comment]
Closing since it is feature complete, although it is not stable yet. Opening other issues about instability.
